name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: Akki-8989/infra-repo/.github/workflows/deploy-be-ecom-orders.yml@main
    with:
      repo_name: be-ecom-orders
      infra_repo: infra-repo
    secrets: inherit
